"""
This script is generated by Gemini and modified by myself
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches

def plot_grid_map(x_grid, y_grid, labels, label_names=None, palette="tab10", ax=None, plot_param={}):
    """
    Plots a 'pixel art' style grid map from 1D grid arrays and flat labels.
    
    Parameters:
    -----------
    x_grid : np.ndarray
        1D array of x coordinates, shape (N,)
    y_grid : np.ndarray
        1D array of y coordinates, shape (M,)
    labels : np.ndarray
        2D array of integer labels of size N * M.
    label_names : dict, optional
        Dictionary mapping integer labels to human-readable strings.
        Example: {0: "Stable", 1: "Unstable"}
    palette : str or list, optional
        Name of a Matplotlib qualitative colormap (e.g., 'tab10', 'Set1', 'Dark2')
        or an explicit list of hex/named colors.
    """
    # 1. Reshape the flat labels into a 2D matrix matching the grid (M rows, N cols)
    # Note: 2D grids in plotting traditionally have shape (len(y), len(x))
    # Z = np.array(labels).reshape(len(y_grid), len(x_grid))
    Z = np.array(labels).transpose()
    
    # 2. Find unique labels present in the data to build a crisp discrete map
    unique_labels = np.unique(Z)
    num_unique = len(unique_labels)
    
    # 3. Handle color mapping dynamically
    if isinstance(palette, list):
        cmap = mcolors.ListedColormap(palette[:num_unique])
    else:
        # Get a standard qualitative colormap from matplotlib
        cmap = plt.get_cmap(palette, num_unique)
        
    # Create a norm that maps each distinct integer label to its own color bucket
    norm = mcolors.BoundaryNorm(
        boundaries=np.append(unique_labels, unique_labels[-1] + 1) - 0.5, 
        ncolors=num_unique
    )

    # 4. Set up the figure layout safely
    if ax is None:
        _, ax = plt.subplots(figsize=(8, 6), layout="constrained")
    
    # 5. Plot the pixel art map
    # shading='auto' handles the grid boundary mapping perfectly
    mesh = ax.pcolormesh(x_grid, y_grid, Z, cmap=cmap, norm=norm, shading='auto')
    
    # 6. Construct the custom discrete legend
    legend_elements = []
    for idx, label_val in enumerate(unique_labels):
        # Extract the specific color assigned to this label bucket
        color = cmap(idx)
        
        # Determine the string name for the legend
        if label_names and label_val in label_names:
            name = label_names[label_val]
        else:
            name = f"Label {label_val}"
            
        # Create a proxy visual rectangle for the legend block
        patch = mpatches.Rectangle((0, 0), 1, 1, facecolor=color, edgecolor='none', label=name)
        legend_elements.append(patch)
        
    # Place the legend neatly outside or on the side of the plot
    ax.legend(handles=legend_elements, loc='upper left', bbox_to_anchor=(1.02, 1), borderaxespad=0)
    
    # 7. Polish visual details
    ax.set_xlim(x_grid.min(), x_grid.max())
    ax.set_ylim(y_grid.min(), y_grid.max())

    title = plot_param.get("title", "Grid Map")
    xlabel = plot_param.get("xlabel", "X-axis")
    ylabel = plot_param.get("ylabel", "Y-axis")
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    
    return ax